server:
  port: 8080

spring:
  datasource:
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwtdb?serverTimezone=UTC&characterEncoding=UTF-8

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info

jwt:
  secretKey: sanghak.and.suengwoo.fff